### ISSUE TITLE
User topics

### ISSUE THREAD

**Issue by innaphv** [MoonSHRD/react-native-app#25]
p2chat после подписки на новые топики (интересы) и нахождения новых пиров с этими топиками запоминает их и группирует собственно по этим топикам, типа как 
dc comics = user1,user3
art-house = user1, user2
Это тоже уже работает 

следовательно остается только прокидывать матчи из p2chat в само приложение, которое вызывает например who_is(user1) - получает собственно matrix профиль и затем это уже отрисовывается на экране

**Comment by ChronosX88** [comment]
Relates to #29.

**Comment by ChronosX88** [comment]
Duplicate of #20
