### ISSUE TITLE
User topics and integration with p2chat module

### ISSUE THREAD

**Issue by innaphv** [MoonSHRD/react-native-app#29]
работа с интересами пользователей и взаимодействие с p2chat/SimpleMdns

- [ ] после того как пользователь ввел какие-либо топики и сохранил - они передаются в p2chat (подразумевается, что сервис стартует вместе со стартом приложения)
- [ ] далее вызывается функция SubscribeToTopic(topic string) куда передаются собственно интересы

далее происходит некоторая магия, обнаруживаются устройства пользователей, они обмениваются между собой интересами и т.п — это все работает в автоматическом режиме внутри p2chat, это то, что уже готово

**Comment by ChronosX88** [comment]
Duplicate of #20
