### ISSUE TITLE
Import 'local chats' module into this app

### ISSUE THREAD

**Issue by innaphv** [MoonSHRD/react-native-app#41]
Импортировать **p2chat-android** как aar модуль в проект (но нужно добавить его в .gitignore, и сделать сборку через Makefile, как в [SimpleMdns](https://github.com/MoonSHRD/SimpleMdns/blob/master/p2mobile/Makefile)), и написать Android-сервис, аналогичный как в [SimpleMdns](https://github.com/MoonSHRD/SimpleMdns/blob/master/app/src/main/java/com/example/simplemdns/P2ChatService.java).

**Comment by ChronosX88** [comment]
Также необходимо отправлять [ReactNative-события](https://facebook.github.io/react-native/docs/native-modules-android#sending-events-to-javascript) на сторону UI при нахождении группы людей по заданному топику.
