### ISSUE TITLE
find matches in this place

### ISSUE THREAD

**Issue by innaphv** [MoonSHRD/react-native-app#48]
every wi-fi point has it's "general" chat
1. if a person is in location of wi-fi point (f.ex. moscow free wi-fi),  we should check if he connected to this wi-fi. If he does, we add him to local "general" chat (moscow free wi-fi) 

2. person can search by himself all chats in his location by gps

**Comment by innaphv** [comment]
Этот экран должен выводить:
[i] Локальную часть, т.е. если пользователь подключен к wi-fi и мы работаем с p2chat

1. все найденные локальные групповые чаты (пользовательские топики с двумя и более пирами)
2. все найденные пользовательские мэтчи (профили)
3. общий чат сети

[ii] "Gps часть"

1. все найденные чаты по указанному ключу

**Comment by Toni111111** [comment]
Общий чат сети на джава старане - сделан.
