### ISSUE TITLE
fix bug with certificate

### ISSUE THREAD

**Issue by innaphv** [MoonSHRD/react-native-app#53]
при логине неверный пароль. при реге - в первый раз никакой реакции, во второе нажатие - уже зарегистрирован пользователь пишет

**Comment by Toni111111** [comment]
how we understand, we have not a bug
Just base data was clean and we just had not registration accounts

**Comment by ChronosX88** [comment]
@Toni111111 наес английский у тебя 😆

**Comment by ChronosX88** [comment]
As for double-clicking, this is the React Native issue.
CC @bahadylbekov
